name: Build + test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: setup bats
      uses: mig4/setup-bats@v1
    - name: checkout code
      uses: actions/checkout@v2
    - name: make all
      run: make all
    - name: make test
      run: make test
